server:
  port: 8081
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  main:
    cloud-platform: kubernetes


management:
  health:
    probes:
      enabled: true
  endpoint:
    health:
      show-details: always
